transaction: equal number of operations and results
The server should execute operations until the first error is
encountered. For every operation, it has to add one result, including a
null result for operations that were not executed.

Database does not exist error is included in this consideration.

Excerpts from the RFC7047.

* About transact:

  The database server executes each of the specified operations in the
  specified order, except if an operation fails, then the remaining
  operations are not executed.

* About results

   In general, "result" contains some number of successful results,
   possibly followed by an error, in turn followed by enough JSON null
   values to match the number of elements in "params".  There is one
   exception: if all of the operations succeed, but the results cannot
   be committed, then "result" will have one more element than "params",
   with the additional element being an <error>.

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>